title:          Cameron Pappas
tagline:        ""
description:    ""
domain:         cjpappas.github.io
#url:            https://cjpappas.github.io 
paginate:       5
permalink:      pretty

author:
  name:  Cameron Pappas
  email: cameron.pappas1@gmail.com

plugins:
  - jekyll-paginate

